### PR TITLE
Auto Captcha Error - Fixed

### PR DESCRIPTION
**Pull request by suumiit**
python -> python3

### CODE REVIEW

**Comment by shivamguys** [comment]
@suumiit  i made changes from python3 to python as general users were not able to use in windows

**Comment by shivamguys** [comment]
Are you encountering any error in your system?

**Comment by suumiit** [comment]
No, all working fine, Thank you

**Comment by shivamguys** [comment]
Glad to hear , do give it a star if you haven't @suumiit 
Appreciate it

**Pull request closed without merging**
