### PR TITLE
[WIP] Add several improvements to booking

### PR DESCRIPTION
**Pull request by drtechie**
**Cypress**
- Use `dayjs` to reliably convert dates. The earlier code gave `Tue, 18 Oct` which wasn't right. Moved the `formatDate` function to a common util.
- Fix the selection of TATKAL. `nth-child(5)` selected DUTY PASS instead of TATKAL. Changes to `nth-child(6)`
- Quickly typing username and password sometimes resulted in characters missing. Changed some of the `cy.type` to input val change. This ensures the text field value is changed in one shot (saving more time).
- JavaScript exceptions in console of IRCTC resulted in Cypress failures. Added a block to ignore them.
- Made the passenger details entry selectors more specific. Added Food choice (relevant for trains like Rajadhani).
- Fail the execution if all seats got booked.

**CAPTCHA server**
- Added relevant dependencies to requirements.txt
- Turned off the warnings since it was getting returned to Cypress.
- Removed all spaces in the CAPTCHA text that is returned.

**Misc**
- Updated readme.
- Fixed typos in functions and comments.
- Removed unnecessary/unused/generated files from checking out to repo.

### CODE REVIEW

**Comment by shivamguys** [comment]
Thanks A Lot Man, for the improvements and Typos 😁
By the way did you tried how fast is the Booking Time...?
Your Experience....
I will merge this once i am back home in a few hours.....

**Comment by drtechie** [comment]
@shivamguys I haven't booked a real ticket yet. I reached the payment QR code.

At 10 AM and 11 AM, the servers behave very erratically.
The entry and selection is definitely faster than a human being. I would say 80% of the time, the automation works fine.
 
 Sometimes the source station selection results are slow, the script gets stuck. 
 CAPTCHA entries are a hit or miss sometimes. Google misses some obvious ones.
 
 I realized I had to handle the FOOD scenario better. Some trains don't have it and some do.
 
 **Please don't merge this now.**
 Marking the PR as WIP.

**Comment by shivamguys** [comment]
yes, Irctc servers are way too messy during Tatkal times.
I was thinking of scheduling the script daily at 10 and 11 to get better data and everything would be recorded in Cypress dashboards....

**Comment by drtechie** [comment]
@shivamguys do check the PR. 
I have added a condition to handle food scenario. 

Scheduling script is a nice idea. 
It will be better to pass the script at the payment selection page if it's running under Cypress dashboard environment.

**Pull request merged**
