### PR TITLE
Faster Captcha Retrieval Using Local Flask Server

### PR DESCRIPTION
**Pull request by hanisntsolo**

### CODE REVIEW

**Review by shivamguys — COMMENTED** [review]
Can we have something better captchas extraction without OCR @hanisntsolo 
I just want to have all these ocr overhead to be removed want something better than this atleast

**Comment by shivamguys** [comment]
Thanks for writing something meaningful for this.   @hanisntsolo

**Comment by shivamguys** [comment]
> > Thanks for writing something meaningful for this.   @hanisntsolo
> > Practically speaking Easy OCR with flask on top is the fastest, if you are looking for local run scenarios.
> 
> Other approach can be : We can create captcha extraction as a service and ask script runner to call it.
> 
> But that also is a network overhead.

Yes and does your machine supports GPU ?
I am not on my system and can you modify the PR to make all comands wrap in a single file and then user need to only run single file and all other commands should be working.... Otherwise it would be overhead for others to first run that then run npm one .. just my thoughts

**Comment by hanisntsolo** [comment]
> > > Thanks for writing something meaningful for this.   @hanisntsolo
> 
> > > Practically speaking Easy OCR with flask on top is the fastest, if you are looking for local run scenarios.
> 
> > 
> 
> > Other approach can be : We can create captcha extraction as a service and ask script runner to call it.
> 
> > 
> 
> > But that also is a network overhead.
> 
> 
> 
> Yes and does your machine supports GPU ?
> 
> I am not on my system and can you modify the PR to make all comands wrap in a single file and then user need to only run single file and all other commands should be working.... Otherwise it would be overhead for others to first run that then run npm one .. just my thoughts 
> 
> 

In an event where GPU is not there the load/share falls back to the cpu. I like the idea of you plugging everything together. So in a single run we have the captcha server as well as booking.

**Comment by hanisntsolo** [comment]
> > > Thanks for writing something meaningful for this.   @hanisntsolo
> 
> > > Practically speaking Easy OCR with flask on top is the fastest, if you are looking for local run scenarios.
> 
> > 
> 
> > Other approach can be : We can create captcha extraction as a service and ask script runner to call it.
> 
> > 
> 
> > But that also is a network overhead.
> 
> 
> 
> Yes and does your machine supports GPU ?
> 
> I am not on my system and can you modify the PR to make all comands wrap in a single file and then user need to only run single file and all other commands should be working.... Otherwise it would be overhead for others to first run that then run npm one .. just my thoughts 
> 
> 

We can have an entry point which handles both in one go!

**Comment by shivamguys** [comment]
> > > > Thanks for writing something meaningful for this.   @hanisntsolo
> > 
> > 
> > > > Practically speaking Easy OCR with flask on top is the fastest, if you are looking for local run scenarios.
> > 
> > 
> > > 
> > 
> > 
> > > Other approach can be : We can create captcha extraction as a service and ask script runner to call it.
> > 
> > 
> > > 
> > 
> > 
> > > But that also is a network overhead.
> > 
> > 
> > Yes and does your machine supports GPU ?
> > I am not on my system and can you modify the PR to make all comands wrap in a single file and then user need to only run single file and all other commands should be working.... Otherwise it would be overhead for others to first run that then run npm one .. just my thoughts
> 
> We can have an entry point which handles both in one go!

Right....

**Comment by hanisntsolo** [comment]
@shivamguys Added the changes pls review!

Now you just give one command and your booking is done!

-- npm run start-booking

If you look at the start captcha and end captcha retrieval timestamp **its just ~ 30sec.** 

[0] 127.0.0.1 - - [20/Nov/2024 **15:38:35**] "POST /extract-text HTTP/1.1" 200 - (First Captcha)
[0] 127.0.0.1 - - [20/Nov/2024 **15:39:08**] "POST /extract-text HTTP/1.1" 200 - (Last Captcha)

`
$ npm run start-booking

> irctc-cypress-automation@3.0.4 start-booking
> concurrently "npm run start-captha-server" "npm run wait-for-captha-server-to-come-up && npm run start-irctc-booking"

[0] 
[0] > irctc-cypress-automation@3.0.4 start-captha-server
[0] > python irctc-captcha-solver/app-server.py --host 0.0.0.0 --port 5000
[0]
[1] 
[1] > irctc-cypress-automation@3.0.4 wait-for-captha-server-to-come-up
[1] > wait-on http://localhost:5000
[1]
[0] Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.
[0]  * Serving Flask app "app-server" (lazy loading)
[0]  * Environment: production
[0]    WARNING: This is a development server. Do not use it in a production deployment.
[0]    Use a production WSGI server instead.
[0]  * Debug mode: off
[0] C:\Users\hanisntsolo-boxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\
easyocr\detection.py:78: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle 
module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch
/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. 
This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they a
re explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
[0]   net.load_state_dict(copyStateDict(torch.load(trained_model, map_location=device)))
[0] C:\Users\hanisntsolo-boxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\
easyocr\recognition.py:169: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pick
le module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pyto
rch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True
`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless the
y are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
[0]   state_dict = torch.load(model_path, map_location=device)
[0]  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[0] 127.0.0.1 - - [20/Nov/2024 15:38:12] "HEAD / HTTP/1.1" 200 -
[1] 
[1] > irctc-cypress-automation@3.0.4 start-irctc-booking
[1] > cypress run --headed --no-exit
[1]
[1] 
[1] 
[1] DevTools listening on ws://127.0.0.1:49504/devtools/browser/ab4e81e4-f6b8-420b-bdbb-eddba5dd918c
[1] 
[1] ====================================================================================================
[1]
[1]   (Run Starting)
[1]
[1]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
[1]   │ Cypress:        13.7.1                                                                         │
[1]   │ Browser:        Electron 118                                                                   │
[1]   │ Node Version:   v20.18.0 (C:\Program Files\nodejs\node.exe)                                    │
[1]   │ Specs:          1 found (irctc.cy.js)                                                          │
[1]   │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
[1]   │ Experiments:    experimentalModifyObstructiveThirdPartyCode=true                               │
[1]   └────────────────────────────────────────────────────────────────────────────────────────────────┘
[1]
[1]
[1] ────────────────────────────────────────────────────────────────────────────────────────────────────
[1]
[1]   Running:  irctc.cy.js                                                                     (1 of 1)
[1] 
[1]
[1]   IRCTC TATKAL BOOKING
[1] Website Fetching completed.........
[1]
[1]
[0] 127.0.0.1 - - [20/Nov/2024 15:38:35] "POST /extract-text HTTP/1.1" 200 -
[1] We have logged in successfully at this stage
[1]
[1]
[1] TATKAL BOOKING NOW OPEN....STARTING FURTHER PROCESS
[1]
[1]
[1] TATKAL TIME STARTED......
[1]
[1]
[1] Passenger Filing STARTED......
[1]
[1]
[1] Age Filing STARTED......
[1]
[1]
[1] .........Solving Second Stage Captchas solveCaptcha()
[1]
[1]
[0] 127.0.0.1 - - [20/Nov/2024 15:39:08] "POST /extract-text HTTP/1.1" 200 -
[1] Solved Second Stage Captchas solveCaptcha()
[1]
[1]
[1]     √ Tatkal Booking Begins...... (49874ms)
[1]
[1]
[1]   1 passing (53s)
[1]
[1] not exiting due to options.exit being false
`

**Comment by shivamguys** [comment]
Looks good to me, the only thing people are saying is easyocr recognises non tatkal time but during tatkal time captchas are much mingled and it fails multiple times which is a bottleneck for us......

**Comment by shivamguys** [comment]
Lets have this a dry run tomorrow during tatkal can you do that for me and lets discuss the performance then how optimal it is after the changes ....
Don't forget to record it with the cypress logs so that we can see where its lagging....     @hanisntsolo

**Comment by hanisntsolo** [comment]
> Lets have this a dry run tomorrow during tatkal can you do that for me and lets discuss the performance then how optimal it is after the changes ....
> 
> Don't forget to record it with the cypress logs so that we can see where its lagging....     @hanisntsolo 

I'm not sure if I can wake up before Tatkal. You can checkout the PR if you want to check performance around Tatkal timings, but you see the initial requirement was to have a flask server so that Cuda overhead using exec can be avoided.

I might be able to grab some logs next Tuesday.

**Comment by hanisntsolo** [comment]
Also there are more optimal ocrs available in the market so if you are planning to have a better ocr create an issue and we can check that on a separate development effort.

**Comment by shivamguys** [comment]
Merging it now.... Thanks

**Pull request merged**
