### PR TITLE
Booking improvements

### PR DESCRIPTION
**Pull request by drtechie**
**Added Boarding station option**
- Some trains show tickets "NOT AVAILABLE" when booking tatkal between intermediate stations. In such trains, one has to book a tatkal from the starting station and change the boarding station to the intermediate station.
- Added support for BOARDING_STATION, this attribute can be left null if not required. Otherwise, the name of the station can be used.

**Ensure the click is 10 AM / 11 AM when booking opens.**
- Earlier the script clicked the availability every 1.9 seconds. Since the server is too slow around 10 AM, valuable time is lost.
- This change ensures that the click is made at exactly 10 AM!

**Option for manual CAPTCHA entry**
- Google text detection is unreliable. If it's wrong, valuable time is lost. It takes way too long for the next CAPTCHA to load.
- Manual captcha option if kept true will require manual intervention from the user.

**Bug fix**
- Missed index variable in food choice, added the same.

### CODE REVIEW

**Comment by shivamguys** [comment]
Will merge this after checking any test cases for the sample stations?
@drtechie

**Comment by drtechie** [comment]
@shivamguys made more improvements, edited the PR description too.

**Comment by shivamguys** [comment]
Will look into it, busy schedules these days

**Comment by shivamguys** [comment]
performing a live run with this.....i dont know but taking risk

suspect something will mess with this line 
        cy.get('div.h_head1', {timeout: 300000}).should('include.text', exactTimeToOpen)

**Comment by shivamguys** [comment]
@drtechie  this manual captcha interaction is awesome thanks a ton for improving this....

**Comment by drtechie** [comment]
@shivamguys login around 9.57 or so and wait for the click to happen at exactly 10 AM.
Irctc servers and login sessions are so unreliable. Good luck. 🤞🏾

**Comment by shivamguys** [comment]
thanks buddy @drtechie

**Comment by drtechie** [comment]
```
cy.get('div.h_head1', {timeout: 300000}).should('include.text', exactTimeToOpen)
```

That line is to wait for the clock to turn 10 AM. Hope it works. 😄

**Comment by shivamguys** [comment]
yup

**Comment by shivamguys** [comment]
trying now running the script @drtechie

**Comment by shivamguys** [comment]
image


@drtechie  suspected worked

**Comment by shivamguys** [comment]
theres a problem

**Comment by drtechie** [comment]
How did you reach this page?
The wait was on the train search list page. 🤔

**Pull request merged**
